source "http://rubygems.org"

gem "rails", "3.0.5"
gem "sqlite3"

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'
  gem 'prawn', "0.8.4"
  gem 'autotest'
  gem 'rspec'
  gem 'haml'
  gem 'steak'
  gem "capybara", ">= 0.4.0"
